abbrmap = {
    "ahu": ["air", "handler", "unit"],
    "vav": ["variable", "volume", "box"],
    "fcu": ["fan", "coil", "unit"],
    "avg": ["average"],
    "cmd": ["command"],
    "elec": ["electrical"],
    "equip": ["equipment"],
    "freq": ["frequency"],
    "occ": ["occupied"],
    "rtu": ["rootftop", "unit"],
    "roof": ["rooftop"],

    "sp": ["setpoint"],
    "spt": ["setpoint"],
    "stpt": ["setpoint"],

    "temp": ["temperature"],
    "tmp": ["temperature"],
    "t": ["temperature"],
    "unocc": ["unoccupied"],
    "volt": ["voltage"],
    "ctl": ["control"],

    "cfm": ["flow"],

    "sa": ["supply", "air"],
    "ea": ["exhaust", "air"],
    "da": ["discharge", "air"],
    "oa": ["outside", "air"],
    "ra": ["return", "air"],

    "sat": ["supply", "air", "temperature"],
    "eat": ["exhaust", "air", "temperature"],
    "dat": ["discharge", "air", "temperature"],
    "oat": ["outside", "air", "temperature"],
    "rat": ["return", "air", "temperature"],

    "sap": ["supply", "air", "pressure"],
    "eap": ["exhaust", "air", "pressure"],
    "dap": ["discharge", "air", "pressure"],
    "oap": ["outside", "air", "pressure"],
    "rap": ["return", "air", "pressure"],

    "sf": ["supply", "fan"],
    "ef": ["exhaust", "fan"],
    "df": ["discharge", "fan"],
    "of": ["outside", "fan"],
    "rf": ["return", "fan"],

    "sup": ["supply"],
    "dis": ["discharge"],
    "ex": ["exhaust"],
    "ret": ["return"],

    "hw": ["hot", "water"],
    "chw": ["chilled", "water"],

    "z": ["zone"],
    "zn": ["zone"],
    
    'mat': ['mixed', 'air', 'temperature'],
    'wcadj': ['warm/cool', 'adjust'],
    'sapﬂ': ['static', 'pressure'],
    'znt': ['zone', 'space', 'temperature'],
    
    'htgo': ['heating', 'valve', 'analog', 'signal'],
    'clgo': ['cooling', 'valve', 'analog', 'signal'],
    'sfo': ['supply', 'fan', 'inlet', 'vane', 'vfd', 'signal'],
    'sfs': ['supply', 'fan', 'status'],
    'rfs': ['return', 'fan', 'status'],
    'smk': ['smoke', 'detector'],
    'sds': ['smoke', 'detector'],
    'dcdb': ['discharge', 'cooling', 'deadband'],
    'dcit': ['discharge', 'cooling', 'intergration'],
    'dcpb': ['discharge', 'cooling', 'proportional', 'band'],
    'depb': ['discharge', 'economizer', 'proportional', 'band'],
    'dhdb': ['discharge', 'heating', 'dead', 'band'],
    'dll': ['discharge', 'low', 'limit'],
    'disrb': ['discharge', 'reset', 'band'],
    'rhl': ['return', 'air', 'high', 'limit'],
    'retrb': ['return', 'reset', 'band'],
    'swovdif': ['economizer', 'switchover', 'differential'],
    'dbswov': ['economizer', 'switchover', 'setpoint'],
    'minpossp': ['economizer', 'minimum', 'position'],
    'malldb': ['mixed', 'air', 'low', 'limit', 'dead', 'band'],
    'mallit': ['mixed', 'air', 'low', 'limit', 'integration'],
    'mallo': ['mixed', 'air', 'low', 'limit', 'offset'],
    'mallpb': ['mixed', 'air', 'low', 'limit', 'proportional', 'band'],
    'mall': ['mixed', 'air', 'lowlimit', 'setpoint'],
    'ucncdf': ['unoccupied', 'cooling', 'differential'],
    'ucncsp': ['unoccupied', 'cooling', 'setpoint'],
    'ucnhdf': ['unoccupied', 'heating', 'differential'],
    'ucnhsp': ['unoccupied', 'heating', 'setpoint'],
    'spdb': ['static', 'pressure'],
    'spdw': ['static', 'pressure', 'derivitive', 'weight'],
    'spit': ['static', 'pressure', 'integration'],
    'sppb': ['static', 'pressure', 'proportional', 'band'],
    'spset': ['static', 'pressure', 'setpoint'],
    'sprampst': ['static', 'pressure', 'output', 'ramp'],
    'zpb': ['zone', 'proportional', 'band'],
    'zntsp': ['zone', 'temperature', 'setpoint'],
    'ahusp': ['calculated', 'discharge', 'setpoint'],
    'occc': ['occupied', 'command'],
    'sdwnc': ['shutdown', 'command'],
    'wcc': ['warmup', 'command'],
    'econs': ['economizer', 'status'],
    'occs': ['occupied', 'status'],
    'restasts': ['status', 'of', 'restart', 'delay'],
    'sdwns': ['shutdown', 'status'],
    'sfa': ['supply', 'fan', 'alarm'],
    'boxhtgc': ['box', 'heating', 'command'],
    'shtgcﬂ': ['supplemental', 'heating', 'command'],
    'htgminfl': ['heating', 'minimum', 'cfm', 'setpoint'],
    'commonsp': ['common', 'setpoint'],
    'clgbias': ['active', 'cooling', 'bias'],
    'cmaxflo': ['maximum', 'cooling', 'cfm', 'setpoint'],
    'ocmncsp': ['occupied', 'cooling', 'minimum', 'cfm', 'setpoint'],
    'ucmncsp': ['unoccupied', 'cooling', 'minimum', 'cfm', 'setpoint'],
    'wmupmin': ['warmup', 'cfm', 'setpoint'],
    'htgbias': ['active', 'heating', 'bias'],
    'occhtgfl': ['occupied', 'heating', 'cfm', 'setpoint'],
    'unchmax': ['unoccupied', 'cooling', 'maximum', 'cfm', 'setpoint'],
    'occcbias': ['occupied', 'cooling', 'bias'],
    'stbycbia': ['standby', 'cooling', 'bias'],
    'unoccbia': ['unoccupied', 'cooling', 'bias'],
    'occhbias': ['occupied', 'heating', 'bias'],
    'stbyhbia': ['standby', 'heating', 'bias'],
    'boxmode': ['current', 'box', 'mode'],
    'htgmode': ['current', 'heating', 'mode'],
    'onochbia': ['unoccupied', 'heating', 'bias'],
    'pkupgain': ['pickup', 'gain'],
    'supflow': ['cfm', 'supply', 'flow'],
    'supflosp': ['calculated', 'cfm', 'setpoint'],
    'bhoutput': ['box', 'heat', 'output'],
    'shoutput': ['supplemental', 'heat', 'output'],
    'wtrflush': ['water', 'flush', 'command'],
    'boxelec': ['electrical', 'heat', 'protection', 'enabled'],
    'acreq': ['autocalibration', 'required'],
    'acact': ['autocalibration', 'in', 'process'],
}
